export default {
  title: 'Default Variant',
  name: 'variantDefaultContent',
  type: 'object',
  description: `This information is sync'd from Shopify and should not be modified here but is mostly just a reference.`,
  fields: [
    {
      title: 'Title',
      name: 'title',
      readOnly: true,
      type: 'string',
    },
    {
      name: 'variantTitle',
      title: 'Variant Title',
      type: 'string',
    },

    {
      name: 'id',
      title: 'ID',
      type: 'string',
      description: 'This comes from Shopify and cannot be changed',
      readOnly: true,
      hidden: true,
    },
    {
      name: 'productId',
      title: 'Product ID',
      type: 'number',
      description: 'This comes from Shopify and cannot be changed',
      readOnly: true,
      hidden: true,
    },
    {
      name: 'variantId',
      title: 'Variant ID',
      type: 'number',
      description: 'This comes from Shopify and cannot be changed',
      readOnly: true,
      hidden: true,
    },
    {
      title: 'Weight in grams',
      name: 'grams',
      readOnly: true,
      type: 'number',
    },
    {
      title: 'Price',
      name: 'price',
      readOnly: true,
      type: 'string',
    },
    {
      title: 'SKU',
      name: 'sku',
      readOnly: true,
      type: 'string',
    },
    {
      title: 'Taxable',
      name: 'taxable',
      readOnly: true,
      type: 'boolean',
    },
    {
      title: 'Inventory Policy',
      name: 'inventoryPolicy',
      readOnly: true,
      type: 'string',
    },
    {
      title: 'Inventory Quantity',
      name: 'inventoryQuantity',
      readOnly: true,
      type: 'number',
    },
    {
      title: 'Bar code',
      name: 'barcode',
      readOnly: true,
      type: 'string',
    },
  ],
};
